---
- name: Get facts
  hosts: localhost
  ignore_errors: true

  tasks:
    - name: Get facts of {{ ansible_hostname }}
      debug:
        var: hostvars[inventory_hostname]

    - name: System details
      debug: msg="{{ item }}"
      with_items:
        - "{{ ansible_distribution }}"
        - "{{ ansible_distribution_version }}"
        - "{{ ansible_distribution_major_version }}"
...

