name: Deploy with Ansible
on:
  push:
    branches: [ "main" ] # Trigger on pushes to main branch
  schedule:
    - cron: '0 0 * * *' # Optional: hourly sync or midnight '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook get_facts.yml --private-key private_key.pem -u ${{ secrets.ANSIBLE_USER }}
          # ansible-playbook -i inventory/hosts.ini playbooks/deploy_web_server.yml --private-key private_key.pem -u ${{ secrets.ANSIBLE_USER }}
